routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('command', function () {
    \Artisan::call('migrate');
    dd("Done");
});


Route::group(['middleware' => ['role']], function(){

    Route::get('/', 'WelcomeController@index')->name('welcome.index');
    Route::get('/ads.txt', 'WelcomeController@adsTxt')->name('welcome.adsTxt');
    
    Route::resource('welcome', 'WelcomeController');
    Auth::routes();
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('admin', 'Admin\AdminController');
    Route::resource('image/upload', 'Admin\ImagesController');
    Route::resource('category', 'Admin\CategoryController');
    Route::put('category-name/{category}', 'Admin\CategoryController@updateName')->name('category.name.update'); 
   
    Route::put('category/setOnWelcome/{id}', 'Admin\CategoryController@setOnWelcome')->name('category.setOnWelcome'); 
    
    Route::resource('post', 'Admin\PostController')->except([
        'create'
    ]); 
    Route::get('/post/create/{id}', 'Admin\PostController@create')->name('post.create'); 
    Route::put('/post/setOnCategory/{id}', 'Admin\PostController@setOnCategory')->name('post.setOnCategory'); 
    Route::resource('draft', 'Admin\DraftController');
    Route::resource('aprove', 'Admin\AproveController');
    Route::get('/aprove/showRejected/{id}', 'Admin\AproveController@showRejected')->name('aprove.showRejected'); 
    Route::resource('welcomeset', 'Admin\WelcomeSettingsController');
    Route::get('/welcomeset/firstSlidetGet/{id}', 'Admin\WelcomeSettingsController@firstSlidetGet')->name('welcomeset.firstSlidetGet'); 

    Route::PUT('welcomeset/updateFirstSlider/{id}', 'Admin\WelcomeSettingsController@updateFirstSlider')->name('welcomeset.updateFirstSlider'); 
    
    
    
    Route::resource('ucategory', 'User\CategoryController');
    Route::resource('articles', 'User\PostController');
    Route::resource('uposts', 'User\PostController');

    Route::resource('redactor', 'Redactor\RedactorController');






    
    
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name','index'
    ];

    static function getLastIndex()
    {
        return self::orderBy('index', 'desc')->first()->index;
    }

    // public function lang(){
    //     return $this->belongsTo('App\Lang','lang_id');
    // }

    public function posts(){
        return $this->hasMany('App\Post',"cat_id")->where('aprove',1)->where('draft',0)->orderBy('updated_at', 'desc');
    }

    public function draft(){
        return $this->hasMany('App\Post',"cat_id")->where('draft',1)->orderBy('updated_at', 'desc');
    }

    public function userPosts(){
        return $this->hasMany('App\Post',"cat_id")->where('aprove',1)->where('draft',0)->where('category_head',0)->orderBy('updated_at', 'desc');
    }
    
    public function headPost(){
        return $this->hasOne('App\Post',"cat_id")->where('aprove',1)->where('draft',0)->where('category_head',1);
    }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;
    
    // const table = 'posts';
    // protected $table = self::table;
    // protected $primaryKey = 'id';

    protected $fillable = [
        'title','description','cat_id','img','user_id','draft'
    ];

    protected $casts = [
        'created_at' => 'datetime:d-month-Y',
    ];

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function category(){
        return $this->belongsTo('App\Category','cat_id');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;


use App\Post;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('index', 'asc')->get();
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $index = Category::getLastIndex() + 1;
        $category = Category::create([
            'name' => $request['category'],
            'index' => $index
        ]);
      
        $html = view('admin.categories.components.newCategoryLi', compact('category'))->render();
        return json_encode($html);
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category=Category::find($id);
        $posts = Post::where('cat_id', $id)->where('aprove',1)->where('draft',0)->orderBy('updated_at', 'desc')->paginate(6);
        return view('admin.categories.show', compact('id', 'posts','category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    { 
        $pass = 'false';
        if ($request['data'] == 'up' && $request['index'] != Category::orderBy('index', 'asc')->first()->index) // daca este egal cu primul element din lista, nu faci nimic
        {
            $saveCategory = Category::orderBy('index', 'desc')->where('index', '<', $request['index'])->first(); // alage primul cel mai mic element dupa request['index']
            $category -> update([
                'index' => $saveCategory->index
            ]);

            $saveCategory -> update([
                'index' => $request['index']
            ]);

            $pass = 'true';

        } else if ($request['data'] == 'down' && $request['index'] != Category::orderBy('index', 'desc')->first()->index) // daca este egal cu ultimul element din lista, nu faci nimic
        {
            $saveCategory = Category::orderBy('index', 'asc')->where('index', '>' ,$request['index'])->first(); // alage primul cel mai mare element dupa request['index']
            $category->update([
                'index' => $request['index'] + 1
            ]);

            $saveCategory->update([
                'index' => $request['index']
            ]);

            $pass = 'true';
        }
        if ($pass == 'true') {
            $categories = Category::orderBy('index', 'asc')->get();
            $html = view('admin.categories.components.updatedIndex', compact('categories'))->render();
            return json_encode($html);
        } else
            return 0;
          
    }
    
    public function updateName(Request $request, Category $category)
    {
        $category->update([
            'name' => $request['name']
        ]);
        $html = view('admin.categories.components.updatedCategoryName', compact('category'))->render();
            return json_encode($html);
        return 1;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        $categories = Category::orderBy('index', 'asc')->get();
        $html = view('admin.categories.components.updatedIndex', compact('categories'))->render();
        return json_encode($html);
    }

    public function setOnWelcome($id){
        $categories=Category::all();
        foreach($categories as $category){
            $category->on_welcome=0;
            $category->save();
        }
        Category::where('id',$id)->update([
            'on_welcome'=>1
        ]);
        return 1;
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use Auth;
use File;
use App\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request )
    {
        dd($request->all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        return view('admin.categories.posts.create', compact('id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $post = Post::create([
            'title' => $request['title'],
            'description' => $request['description'],
            'cat_id' => $request['catID'],
            'user_id' => Auth::user()->id,
            'draft'=>$request['draft']
        ]);

        $idString = (string)$post->id;
        $title=str_replace("?","", str_replace("\\","", str_replace("/","",strtolower ($postPage->title))))."-echo-".$idString  ;
        $title = explode(" ", $title);
        $newSeoTitle = "";
        foreach($title as $t){
            if($newSeoTitle == ""){
                $newSeoTitle = $newSeoTitle.$t."-";
            }else{
                $newSeoTitle = $newSeoTitle."-".$t;
            }
        }
       
        Post::where('id',$post->id)->update([
            "seo_link" =>$newSeoTitle
        ]);
    

        $image1 = $request['img1'];  
        $virgula=strrpos($image1,',');
        $str=substr($image1, 0,$virgula+1);
        $bara=strrpos($image1,'image/');
        $punct=strrpos($image1,';base64');
        $extension= substr($str, $bara+6,$punct-$bara-6);
        $image1 = str_replace('data:image/'.$extension.';base64,', '', $image1);
        $image1 = str_replace(' ', '+', $image1);

        $imageName = 'post-'.$post->id.'-base.'.$extension;
       
        File::put('posts/images/'. $imageName, base64_decode($image1));
        
        $post->img=$imageName;
        $post->save();
        
       

        $image2 = $request['img2'];  
        $virgula=strrpos($image2,',');
        $str=substr($image2, 0,$virgula+1);
        $bara=strrpos($image2,'image/');
        $punct=strrpos($image2,';base64');
        $extension= substr($str, $bara+6,$punct-$bara-6);
        $image2 = str_replace('data:image/'.$extension.';base64,', '', $image2);
        $image2 = str_replace(' ', '+', $image2);

        $imageName2 = 'post-'.$post->id.'.'.$extension;
        File::put('posts/images/'. $imageName2, base64_decode($image2));
        
        $post->img2=$imageName2;
        $post->save();
        
        if($request['draft']==1){
            return route('draft.show', $request['catID']);
        }else{
            return route('category.show', $request['catID']);
        }
       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post=Post::find($id);
        $posts=Post::where('cat_id',$post->cat_id)->where('aprove',1)->where('id','<>',$id)->orderBy('updated_at', 'desc')->get();
        if(count($posts)>=4){
            $posts=Post::where('cat_id',$post->cat_id)->where('aprove',1)->where('id','<>',$id)->orderBy('updated_at', 'desc')->take(3)->get();
        }
        return view('admin.categories.posts.show', compact('post',"posts"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post=Post::find($id);
        return view('admin.categories.posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post=Post::find($id);
        $validation = Validator::make($request->all(), [
            'image' => 'required'
        ]);
        if(!$validation->fails()){
            $image1 = $request['img1'];  
            $virgula=strrpos($image1,',');
            $str=substr($image1, 0,$virgula+1);
            $bara=strrpos($image1,'image/');
            $punct=strrpos($image1,';base64');
            $extension= substr($str, $bara+6,$punct-$bara-6);
            $image1 = str_replace('data:image/'.$extension.';base64,', '', $image1);
            $image1 = str_replace(' ', '+', $image1);
    
            $imageName = 'post-'.$post->id.'-base.'.$extension;
           
            File::put('posts/images/'. $imageName, base64_decode($image1));
            $post->img=$imageName;
            $post->save();
        }

        $validation = Validator::make($request->all(), [
            'image_2' => 'required'
        ]);
        if(!$validation->fails()){

            $image2 = $request['img2'];  
            $virgula=strrpos($image2,',');
            $str=substr($image2, 0,$virgula+1);
            $bara=strrpos($image2,'image/');
            $punct=strrpos($image2,';base64');
            $extension= substr($str, $bara+6,$punct-$bara-6);
            $image2 = str_replace('data:image/'.$extension.';base64,', '', $image2);
            $image2 = str_replace(' ', '+', $image2);

            $imageName2 = 'post-'.$post->id.'.'.$extension;
            File::put('posts/images/'. $imageName2, base64_decode($image2));
            $post->img2=$imageName2;
            $post->save();
        }

        Post::where('id',$id)->update([
            'title' => $request['title'],
            'description' => $request['description'],
        ]);

        return route('post.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post=Post::find($id);
        Post::where('id',$id)->delete();
        return route('category.show', $post->cat_id);
    }

    public function setOnCategory($id){
        $post=Post::find($id);
        Post::where('cat_id',$post->cat_id)->update([
            'category_head'=>0
        ]);

        Post::where('id',$id)->update([
            'category_head'=>1
        ]);

        return 1;
    }
    
}   

app/Http/Controllers/User/CategoryController.php
<?php

namespace App\Http\Controllers\User;

use App\Post;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $posts=Post::inRandomOrder()->where('draft',0)->where('aprove',1)->where('category_head',0)->get();
        if(count($posts)>=4){
            $posts=Post::inRandomOrder()->where('draft',0)->where('aprove',1)->where('category_head',0)->take(3)->get();
        }
        $category=Category::find($id);
        $categoryPosts=Post::where('cat_id',$id)->where('draft',0)->where('aprove',1)->where('category_head',0)->orderBy('updated_at', 'desc')->paginate(12);
        return view('category',compact('id','category','posts','categoryPosts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/categories/posts/create.blade.php
@extends('layouts.admin')
@section('content')

    <div class="container add-post-form">
    <form  method="POST" enctype="multipart/form-data" data-draft="0" id='add-post-form' data-url="{{route('post.store')}}" data-id="{{$id}}">
        @method('POST')
        {!! csrf_field() !!}
        <div class="row">
            <div class="col-md-12">
                <textarea type="text" class="form-control" placeholder="Titlul" id='post-title' required></textarea>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p class="h4">Aspect Ratio 1:1 <span style="color:brown; font-weight:bold;">required</span></p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <input type="file" name='image' class='mt-3 main-image' onchange='readURL(this);' required>
            </div>
        </div>

        <div class="img-div row">
            <div class="col-md-12">
                <button type="button" class="btn offset-11 btn-lg d-none close-img-btn "><i
                        class="fas fa-times"></i></button>
                <img id="image-file" src="#" alt="Image" class='d-none mt-1 main-img-style' />
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p class="h4">Aspect Ratio 3:1 <span style="color:brown; font-weight:bold;">required</span></p>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-12">
                <input type="file" name='image_2' class='mt-3 main-image2' onchange='readURL2(this);' required>
            </div>
        </div>

        <div class="img-div2 row">
            <div class="col-md-12">
                <button type="button" class="btn offset-11 btn-lg d-none close-img-btn2 "><i
                        class="fas fa-times"></i></button>
                <img height="auto" id="image-file2" src="#" alt="Image" class='d-none max-vh-50 mt-1 main-img-style' />
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <hr>
            </div>
        </div>
      
        <div class="mt-3 row">
            <div class="col-md-12">
                <textarea name="content" id="editor"></textarea>
            </div>
        </div>
        <div class="row my-3">
            <div class="col-md-6">
                <button class="btn btn-warning float-right btn-block" id="add-post-draft" type="submit"><i class="fas fa-pencil-ruler mr-2"></i>Draft</button>
            </div>
            <div class="col-md-6">
                <button class="btn btn-primary btn-block float-right ml-2" id="add-post-btn-add" type="submit"><i class="fas fa-file-alt mr-2"></i>Add</button>
            </div>
        </div>
    </form>
    
   
    </div>
   
@endsection

resources/views/admin/categories/posts/edit.blade.php
@extends('layouts.'.Auth::user()->userRole->role->default_page)
@section('content')

<div class="container">
    <form enctype="multipart/form-data" data-draft="0" id='update-post-form' data-url="{{route('post.update',$post->id)}}">
        @method('PATCH')
        {{-- @csrf --}}
        <div class="row">
            <div class="col-md-12">
                <textarea type="text" class="form-control" placeholder="Titlul" id='post-title'>{{$post->title}}</textarea>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <input type="file" name='image' class='mt-3 main-image' onchange='readURL(this);'>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <p class="h4">Aspect Ratio 1:1</p>
            </div>
        </div>

        <div class="img-div row">
            <div class="col-md-12">
                <img id="image-file" style="width:350px; height:350px;" src="/posts/images/{{$post->img}}" alt="Image" class='max-vh-50 mt-1 main-img-style' />
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <p class="h4">Aspect Ratio 3:1</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <input type="file" name='image_2' class='mt-3 main-image2' onchange='readURL2(this);'>
            </div>
        </div>

        <div class="img-div2 row">
            <div class="col-md-12">
                <img height="auto" id="image-file2" src="/posts/images/{{$post->img2}}" alt="Image" class='w-100 max-vh-50 mt-1 main-img-style' />
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <hr>
            </div>
        </div>
      
        <div class="mt-3 row">
            <div class="col-md-12">
                <textarea name="content" id="editor">{{$post->description}}</textarea>
            </div>
        </div>
        <div class="row my-3">
            <div class="col-md-12">
                <button class="btn btn-primary float-right ml-2 btn-block" type="submit"><i class="fas fa-save mr-2"></i>Save</button>
            </div>
        </div>
    </form>
</div>
   
@endsection

resources/views/admin/categories/posts/show.blade.php
@extends('layouts.'.Auth::user()->userRole->role->default_page)
@section('content')

<div class="container">

    <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('welcome.index')}}">ECHO</a></li>
            <li class="breadcrumb-item"><a href="{{route('ucategory.show',$post->category->id)}}">{{$post->category->name}}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{$post->title}}</li>
        </ol>
    </nav>
    <div class="row mb-3">
        <div class="col-md-12">
            <button data-url="{{route('post.destroy',$post->id)}}" type="button" id="delete-btn-post" class="btn link btn-danger btn-block">Delete</button>
        </div>
    </div>
    @if($post->draft==1)
        <div class="row">
            <div class="col-md-12">
                <button id="post-draft-btn" data-url="{{route('draft.update',$post->id)}}" class="btn-primary btn btn-block"><i class="fas fa-file-alt mr-2"></i>Post</button>
            </div>
        </div>
    @endif
    <div class="row">

        <div class="col-lg-8">
            <h1 class="mt-4 text-indent">{{$post->title}} <a href="{{route('post.edit', $post->id)}}"><i class="fas fa-pencil-alt"></i></a></h1> 
            <p class="lead">
                de <a href="#">{{$post->user->name}}</a>
                <span class="float-right">Postat pe {{date_format($post->created_at, 'd.m.y , g:i a')}}</span>
            </p>
            <img class="w-100 max-vh-50 img-fluid" src="/posts/images/{{$post->img2}}" alt="">
            <hr>
            <div class="text-indent">
                {!!$post->description!!}
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="fb-comments" data-href="{{route(Route::currentRouteName(),$post->id)}}" data-width="100%" data-numposts="5"></div>
                </div>
            </div> 
        </div>
        <div class="col-md-4 mt-5">
            @foreach ($posts as $post)
                <a href="{{route('post.show', $post->id)}}">
                    <div class="mb-3 border-0 card bg-dark text-dark font-weight-bold">
                        <img src="/posts/images/{{$post->img}}" height="300" class="card-img" alt="...">
                        <div class="background-post">
                        </div>
                        <div class="card-img-overlay ">
                            <h3 class="card-title card-title-post">{{$post->title}}</h3>
                            <p class="align-items-end card-text card-text-post">Adăugat de {{$post->user->name}}</p>
                        </div>
                    </div>
                </a>
            @endforeach
        </div>

    </div>
</div>

@endsection