routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('command', function () {
    \Artisan::call('migrate');
    dd("Done");
});


Route::group(['middleware' => ['role']], function(){

    Route::get('/', 'WelcomeController@index')->name('welcome.index');
    Route::get('/ads.txt', 'WelcomeController@adsTxt')->name('welcome.adsTxt');
    
    Route::resource('welcome', 'WelcomeController');
    Auth::routes();
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('admin', 'Admin\AdminController');
    Route::resource('image/upload', 'Admin\ImagesController');
    Route::resource('category', 'Admin\CategoryController');
    Route::put('category-name/{category}', 'Admin\CategoryController@updateName')->name('category.name.update'); 
   
    Route::put('category/setOnWelcome/{id}', 'Admin\CategoryController@setOnWelcome')->name('category.setOnWelcome'); 
    
    Route::resource('post', 'Admin\PostController')->except([
        'create'
    ]); 
    Route::get('/post/create/{id}', 'Admin\PostController@create')->name('post.create'); 
    Route::put('/post/setOnCategory/{id}', 'Admin\PostController@setOnCategory')->name('post.setOnCategory'); 
    Route::resource('draft', 'Admin\DraftController');
    Route::resource('aprove', 'Admin\AproveController');
    Route::get('/aprove/showRejected/{id}', 'Admin\AproveController@showRejected')->name('aprove.showRejected'); 
    Route::resource('welcomeset', 'Admin\WelcomeSettingsController');
    Route::get('/welcomeset/firstSlidetGet/{id}', 'Admin\WelcomeSettingsController@firstSlidetGet')->name('welcomeset.firstSlidetGet'); 

    Route::PUT('welcomeset/updateFirstSlider/{id}', 'Admin\WelcomeSettingsController@updateFirstSlider')->name('welcomeset.updateFirstSlider'); 
    
    
    
    Route::resource('ucategory', 'User\CategoryController');
    Route::resource('articles', 'User\PostController');
    Route::resource('uposts', 'User\PostController');

    Route::resource('redactor', 'Redactor\RedactorController');






    
    
});

app/Http/Controllers/Admin/AproveController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Post;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AproveController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts=Post::where('aprove',0)->where('draft',0)->paginate(6);
        return view('admin.aprove.index',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category=Category::find($id);
        $posts=Post::where('cat_id',$category->id)->where('aprove',0)->where('draft',0)->paginate(6);
        return view("admin.aprove.inProces",compact('posts','category'));
    }

    public function showRejected($id)
    {
        $category=Category::find($id);
        $posts=Post::where('cat_id',$category->id)->where('aprove',2)->where('draft',0)->paginate(6);
        return view("admin.aprove.rejected",compact('posts','category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($request['aproveStatus']==1){
            Post::where('id',$id)->update([
                'aprove'=>1
            ]);
        }elseif($request['aproveStatus']==2){
            Post::where('id',$id)->update([
                'aprove'=>2
            ]);
        }elseif($request['aproveStatus']==0){
            Post::where('id',$id)->update([
                'aprove'=>0
            ]);
        }
        return 1;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/aprove/inProces.blade.php
@extends('layouts.'.Auth::user()->userRole->role->default_page)
@section('content')
<div class="container-fluid">

    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link py-2 px-2" href="{{route('category.show',$category->id)}}">Postări</a>
        </li>
        <li class="nav-item">
            <a class="nav-link py-2 px-2" href="{{route('draft.show',$category->id)}}">Draft</a>
        </li>
        <li class="nav-item">
            <a class="nav-link py-2 px-2" href="{{route('aprove.showRejected',$category->id)}}">Neaprobate</a>
        </li>
        <li class="nav-item">
            <a class="nav-link py-2 px-2 active" href="{{route('aprove.show',$category->id)}}">În proces</a>
        </li>
    </ul>
    <div class="row mt-2">
        <div class="col-md-12">
            <a href={{route('post.create', $category->id)}} class='round-btn-primary float-right btn-circle'><i class="fas fa-plus"></i></a>
        </div>
    </div>
    
    <div class="row mb-3">
        @foreach ($posts as $post)
            <div class="col-md-4 mt-4">
                <a href="{{route('post.show', $post->id)}}">
                    <div class="card border-0 bg-dark text-dark font-weight-bold">
                        <img src="/posts/images/{{$post->img}}" height="300px" class="card-img" alt="...">
                        <div class="background-post">
                        </div>
                        <div class="card-img-overlay ">
                            <h5 class="card-title card-title-post">{{$post->title}}</h5>
                            <p class="align-items-end card-text card-text-post">Adăugat de {{$post->user->name}}</p>
                        </div>
                    </div>
                </a>
            </div>
        @endforeach
    </div>
    <div class="row">
        <div class="col-md-4">
            {{ $posts->onEachSide(0)->links() }}
        </div>
    </div>
</div>

@endsection

resources/views/admin/aprove/index.blade.php
@extends('layouts.'.Auth::user()->userRole->role->default_page)
@section('content')
<div class="container-fluid">
    <div class="row mb-3">
        @if(count($posts)==0)
        <div class="col-md-12 mt-5 text-center">
            <p class="h2">Nici o postare nouă.</p>
        </div>
        @else
            @foreach ($posts as $post)
                <div class="col-md-4 mt-4">
                    <div class="card border-0 bg-dark text-dark font-weight-bold">
                        <a href="{{route('post.show', $post->id)}}">
                                <img src="/posts/images/{{$post->img}}" height="300px" class="card-img" alt="...">
                            <div class="background-post">
                            </div>
                            <div class="card-img-overlay ">
                                <h3 class="card-title card-title-post">{{$post->title}}</h3>
                                <p class="align-items-end card-text card-text-post">Domeniu: {{$post->category->name}}</p>
                                <p class="align-items-end card-text card-text-post">Adăugat de {{$post->user->name}}</p>
                            </div>
                        </a>
                        <div class="card-body p-0">
                            <div class="row">
                                <div class="col-md-6 pr-0">
                                    <button data-url="{{route('aprove.update',$post->id)}}" data-aprove-status="2" class="btn btn-danger aprove-post-btn btn-block">Reject</button>
                                </div>
                                <div class="col-md-6 pl-0">
                                    <button data-url="{{route('aprove.update',$post->id)}}" data-aprove-status="1" class="btn btn-primary aprove-post-btn btn-block">Aprove</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        @endif
    </div>
    <div class="row">
        <div class="col-md-4">
            {{ $posts->onEachSide(0)->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/admin/aprove/rejected.blade.php
@extends('layouts.'.Auth::user()->userRole->role->default_page)
@section('content')
<div class="container-fluid">

    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link py-2 px-2" href="{{route('category.show',$category->id)}}">Postări</a>
        </li>
        <li class="nav-item">
            <a class="nav-link py-2 px-2" href="{{route('draft.show',$category->id)}}">Draft</a>
        </li>
        <li class="nav-item">
            <a class="nav-link py-2 px-2 active" href="{{route('aprove.showRejected',$category->id)}}">Neaprobate</a>
        </li>
        <li class="nav-item">
            <a class="nav-link py-2 px-2" href="{{route('aprove.show',$category->id)}}">În proces</a>
        </li>
    </ul>
    <div class="row mt-2">
        <div class="col-md-12">
            <a href={{route('post.create', $category->id)}} class='round-btn-primary float-right btn-circle'><i class="fas fa-plus"></i></a>
        </div>
    </div>
    
    <div class="row mb-3">
        @foreach ($posts as $post)
            <div class="col-md-4 mt-4">
                <a href="{{route('post.show', $post->id)}}">
                    <div class="card border-0 bg-dark text-dark font-weight-bold">
                        <img src="/posts/images/{{$post->img}}" height="300px" class="card-img" alt="...">
                        <div class="background-post">
                        </div>
                        <div class="card-img-overlay ">
                            <h5 class="card-title card-title-post">{{$post->title}}</h5>
                            <p class="align-items-end card-text card-text-post">Adăugat de {{$post->user->name}}</p>
                        </div>
                        <div class="card-body p-0">
                            <div class="row">
                                <div class="col-md-12">
                                    <button data-url="{{route('aprove.update',$post->id)}}" data-aprove-status="0" class="btn btn-primary aprove-post-btn btn-block">Resend</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        @endforeach
    </div>
    <div class="row">
        <div class="col-md-4">
            {{ $posts->onEachSide(0)->links() }}
        </div>
    </div>
</div>

@endsection