routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('command', function () {
    \Artisan::call('migrate');
    dd("Done");
});


Route::group(['middleware' => ['role']], function(){

    Route::get('/', 'WelcomeController@index')->name('welcome.index');
    Route::get('/ads.txt', 'WelcomeController@adsTxt')->name('welcome.adsTxt');
    
    Route::resource('welcome', 'WelcomeController');
    Auth::routes();
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('admin', 'Admin\AdminController');
    Route::resource('image/upload', 'Admin\ImagesController');
    Route::resource('category', 'Admin\CategoryController');
    Route::put('category-name/{category}', 'Admin\CategoryController@updateName')->name('category.name.update'); 
   
    Route::put('category/setOnWelcome/{id}', 'Admin\CategoryController@setOnWelcome')->name('category.setOnWelcome'); 
    
    Route::resource('post', 'Admin\PostController')->except([
        'create'
    ]); 
    Route::get('/post/create/{id}', 'Admin\PostController@create')->name('post.create'); 
    Route::put('/post/setOnCategory/{id}', 'Admin\PostController@setOnCategory')->name('post.setOnCategory'); 
    Route::resource('draft', 'Admin\DraftController');
    Route::resource('aprove', 'Admin\AproveController');
    Route::get('/aprove/showRejected/{id}', 'Admin\AproveController@showRejected')->name('aprove.showRejected'); 
    Route::resource('welcomeset', 'Admin\WelcomeSettingsController');
    Route::get('/welcomeset/firstSlidetGet/{id}', 'Admin\WelcomeSettingsController@firstSlidetGet')->name('welcomeset.firstSlidetGet'); 

    Route::PUT('welcomeset/updateFirstSlider/{id}', 'Admin\WelcomeSettingsController@updateFirstSlider')->name('welcomeset.updateFirstSlider'); 
    
    
    
    Route::resource('ucategory', 'User\CategoryController');
    Route::resource('articles', 'User\PostController');
    Route::resource('uposts', 'User\PostController');

    Route::resource('redactor', 'Redactor\RedactorController');






    
    
});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>ECHO</title>
    <link rel="shortcut icon" href="/img/logo-title.png" />
    <link href="{{asset('css/fontawesome-free/all.min.css')}}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">
    <link href="{{asset('css/app.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    <link rel="stylesheet" href="{{asset('css/cropper.css')}}">

</head>

<body>
    <div id="app">
        <div class="fixed-top" id="side-navbar-animation wrapper">
            <div class="pb-3 bg-dark" id="sidebar-wrapper">
                <div class="sidebar-heading text-white">
                    <a href="{{route('welcome.index')}}"><img width="100%" src="/img/echo-logo.png" alt=""></a>
                </div>
                <div class="list-group list-group-flush">
                    <a href="{{route('home')}}" class="list-group-item list-group-item-action text-white text-center bg-dark  @if('admin.index'==Route::currentRouteName()) nav-active @endif">
                        <i class="fas fa-home mr-2"></i>Home</a>
                    <a href="{{route('aprove.index')}}" class="list-group-item list-group-item-action text-white text-center bg-dark @if('aprove.index'==Route::currentRouteName()) nav-active @endif">
                        <i class="fas fa-thumbs-up mr-2"></i>Articles approval
                    </a>
                    <a href="{{route('welcomeset.index')}}" class="list-group-item list-group-item-action text-white text-center bg-dark @if('welcomeset.index'==Route::currentRouteName()) nav-active @endif">
                        <i class="fas fa-cogs mr-2"></i>Welcome settings
                    </a>
                    <a href="{{route('category.index')}}" class="list-group-item list-group-item-action text-white text-center mb-0 pb-0 bg-dark @if('category.index'==Route::currentRouteName()) nav-active @endif">
                        <i class="fas fa-boxes mr-2"></i>Categories managment
                        <hr class="sidebar-divider">
                    </a>
                    <div class="categories">
                        @foreach ($categories as $i=>$category)
                            <a href="{{route('category.show', $category->id)}}" class="@if(count($categories)==$i+1) mb-1 @endif list-group-item list-group-item-action text-white text-center bg-dark  @if(isset($id))@if($category->id==$id) nav-active @endif @endif">
                                {{ $category->name }}
                                @if(count($categories)==$i+1)
                                    <hr class="mb-1 sidebar-divider"> 
                                @endif
                            </a>
                        @endforeach
                    </div>
                </div>
                <div class="input-group mb-3 p-3 d-none" id="input-category" data-toggle="0">
                    <input type="text" class="form-control" aria-label="Categorie" id="category-input">
                    <div class="input-group-append">
                        <button class="btn btn-secondary" type="button" id="add-category-btn"
                            data-url={{route('category.store')}}>Add</button>
                    </div>
                </div>
                <div class="text-center">
                    <button class="round-btn-primary btn-circle" id="plusButton"><i class="fas fa-plus"></i></button>
                </div>
            </div>
            <div id="top-white-navbar">
                <div id="content">
                    <nav class="navbar navbar-expand navbar-light bg-white topbar static-top shadow">
                        <ul class="navbar-nav ml-auto">
                            <form action="{{route('logout')}}" method="POST" class="d-flex p-1">
                                @csrf
                                <button type='submit' class="btn btn-primary">Logout</button>
                            </form>
                        </ul>
                    </nav>
                </div>
            </div>
            <div id="page-content-wrapper">
                <nav class="navbar fixed-top navbar-expand-lg navbar-dark text-white bg-dark border-bottom d-md-none">
                    <a href="{{route('welcome.index')}}" class="navbar-brand">ECHO</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                            <li class="nav-item">
                                <a href="{{route('home')}}" class="nav-link @if('admin.index'==Route::currentRouteName()) active @endif"><i class="fas fa-home mr-2"></i>Home</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('category.index')}}" class="nav-link @if('category.index'==Route::currentRouteName()) active @endif">
                                    <i class="fas fa-boxes mr-2"></i>Categories managment
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('welcomeset.index')}}" class="nav-link @if('welcomeset.index'==Route::currentRouteName()) active @endif">
                                    <i class="fas fa-cogs mr-2"></i>Welcome settings
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('aprove.index')}}" class="nav-link @if('aprove.index'==Route::currentRouteName()) active @endif">
                                        <i class="fas fa-thumbs-up mr-2"></i>Articles approval
                                </a>
                            </li>
                            @foreach ($categories as $category)
                            <li class="nav-item">
                                <a href={{route('category.show', $category->id)}} class="nav-link @if(isset($id))@if($category->id==$id) active @endif @endif">
                                    {{ $category->name }}
                                </a>
                            </li>
                            @endforeach
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <div class="page-wrapper">
            <div class="min-vh-100">
                @yield('content')
            </div>
            <footer class="py-5 bg-dark">
                <div class="container">
                    <p class="m-0 text-center text-white">Copyright &copy; <a href="" target="_blank">SoftChamp Inc</a> 2019</p>
                </div>
            </footer>
        </div>
    </div>
    <script src="/js/jquery/jquery.min.js"></script>
    <script src="/js/bootstrap/bootstrap.bundle.min.js"></script>
    <script src="/js/jquery/jquery.easing.min.js"></script>
    <script src="/js/sb-admin-2.min.js"></script>
    <script src="{{asset('js/script.js')}}"></script>
    <script src="{{asset('js/cropper.js')}}"></script>
    <script src="{{asset('js/app.js')}}"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous"
        src="https://connect.facebook.net/ro_RO/sdk.js#xfbml=1&version=v3.3&appId=406720239939704&autoLogAppEvents=1">
    </script>
</body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @if(isset($postPage))
        {{-- <meta property="fb:app_id"          content="{{str_random(32)}}" />  --}}
        <meta property="og:type"            content="website" /> 
        <meta property="og:url"             content="{{route(Route::currentRouteName(),$postPage->id)}}" /> 
        <meta property="og:title"           content="{{$postPage->title}}" /> 
        <meta property="og:image"           content="{{URL::to('/')}}/posts/images/{{$postPage->img2}}" /> 
        <meta property="twitter:image"  content="{{URL::to('/')}}/posts/images/{{$postPage->img2}}">
        <meta property="og:description"    content="{{ strip_tags($postPage->description) }}" />
        <meta property="description"    content="{{ strip_tags($postPage->description) }}" />
        <meta property="twitter:title" content="{{$postPage->title}}"/>
        <meta property="twitter:description"  content="{{ strip_tags($postPage->description) }}"/>
    @else
        <meta property="type"            content="website" /> 
        <meta property="og:type"            content="website" /> 
        <meta property="og:url"             content="{{URL::to('/')}}" /> 
        <meta property="url"             content="{{URL::to('/')}}" /> 
        <meta property="og:title"           content="ECHO" /> 
        <meta property="title"           content="ECHO" /> 
        <meta property="twitter:image"  content="{{URL::to('/')}}/img/facebook-cover.png">
        <meta property="og:image" content="{{URL::to('/')}}/img/facebook-cover.png">
        <meta property="og:description"    content="Suntem un portal de știri din Republica Moldova, articolele noastre sunt despre cele mai interesante evenimente și noutati din Republica Moldova și intreaga lume. Temele pe care ne străduim să le abordam sunt tehnologiile și businessul. " />
        <meta property="description"    content="Suntem un portal de știri din Republica Moldova, articolele noastre sunt despre cele mai interesante evenimente și noutati din Republica Moldova și intreaga lume. Temele pe care ne străduim să le abordam sunt tehnologiile și businessul. " />
        <meta property="twitter:title" content="ECHO"/>
        <meta property="twitter:description"  content="Suntem un portal de știri din Republica Moldova, articolele noastre sunt despre cele mai interesante evenimente și noutati din Republica Moldova și intreaga lume. Temele pe care ne străduim să le abordam sunt tehnologiile și businessul."/>
    @endif
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>ECHO</title>
    <link rel="shortcut icon" href="/img/logo-title.png" />
    <script src="{{ asset('js/app.js') }}" defer></script>
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="{{asset('css/fontawesome-free/all.min.css')}}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/guest-style.css') }}" rel="stylesheet">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-6092609646755605",
            enable_page_level_ads: true
        });
    </script>

</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a title="HOME - ECHO" class="navbar-brand" href="{{route('welcome.index')}}"><img width="150px" src="/img/echo-logo.png" alt=""></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    @if(Auth::user())
                        <li class="nav-item">
                            <a title="Home" href="{{route('home')}}" class="nav-link"><i class="fas fa-home mr-2"></i>Home</a>
                        </li>
                    @endif
                    @foreach ($categories as $category)
                        <li class="nav-item @if(isset($id))@if($category->id==$id) active @endif @endif">
                            <a title="{{ $category->name }}" href="{{route('ucategory.show', $category->id)}}" class="nav-link">{{ $category->name }}</a>
                        </li>
                    @endforeach
                </ul>
            </div>
        </div>
    </nav>

    <div id="app">
        <div class="container">
            <div class="min-vh-100">
                @yield('content')
            </div>
        </div>
        <footer class="mt-3 py-5 bg-dark">
            <div class="container">
                <p class="m-0 text-center text-white">
                    Copyright &copy; <a href="" target="_blank">SoftChamp Inc</a> 2019
                </p>
                <div class="fb-share-button" data-href="https://echo.md/" data-layout="button_count"></div>
            </div>
        </footer>
    </div>

    <!-- Global site tag (gtag.js) - Google Analytics -->

    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.4&appId=241110544128";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));

    </script>
    <script src="{{asset('js/jquery/jquery.min.js')}}"></script>
    <script src="{{asset('js/cscript.js')}}"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143374596-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-143374596-1');

    </script>
    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.4&appId=241110544128";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));

    </script>

    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-6092609646755605",
        enable_page_level_ads: true
    });
    </script>
    <script async custom-element="amp-auto-ads"
        src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
    </script>
    <amp-auto-ads type="adsense"
        data-ad-client="ca-pub-6092609646755605">
    </amp-auto-ads>
</body>

</html>

resources/views/layouts/redactor.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>ECHO</title>
   <link rel="shortcut icon" href="/img/logo-title.png" />
    <link href="{{asset('css/fontawesome-free/all.min.css')}}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">
    <link href="{{asset('css/app.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    <link rel="stylesheet" href="{{asset('css/cropper.css')}}">

</head>

<body>
    <div id="app">
        <div class="fixed-top" id="side-navbar-animation wrapper">
            <div class="pb-3 bg-dark" id="sidebar-wrapper">
                <div class="sidebar-heading text-white">
                    <a href="{{route('welcome.index')}}"><img width="100%" src="/img/echo-logo.png" alt=""></a>
                </div>
                <div class="list-group list-group-flush">
                    <a href="{{route('home')}}" class="list-group-item list-group-item-action text-white text-center bg-dark  @if('admin.index'==Route::currentRouteName()) nav-active @endif">
                        <i class="fas fa-home mr-2"></i>Home</a>
                    <div class="categories">
                        @foreach ($categories as $i=>$category)
                            <a href="{{route('category.show', $category->id)}}" class="@if(count($categories)==$i+1) mb-1 @endif list-group-item list-group-item-action text-white text-center bg-dark  @if(isset($id))@if($category->id==$id) nav-active @endif @endif">
                                {{ $category->name }}
                                @if(count($categories)==$i+1)
                                    <hr class="mb-1 sidebar-divider"> 
                                @endif
                            </a>
                        @endforeach
                    </div>
                </div>
            </div>
            <div id="top-white-navbar">
                <div id="content">
                    <nav class="navbar navbar-expand navbar-light bg-white topbar static-top shadow">
                        <ul class="navbar-nav ml-auto">
                            <form action="{{route('logout')}}" method="POST" class="d-flex p-1">
                                @csrf
                                <button type='submit' class="btn btn-primary">Logout</button>
                            </form>
                        </ul>
                    </nav>
                </div>
            </div>
            <div id="page-content-wrapper">
                <nav class="navbar fixed-top navbar-expand-lg navbar-dark text-white bg-dark border-bottom d-md-none">
                    <a href="{{route('welcome.index')}}" class="navbar-brand">ECHO</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                            <li class="nav-item">
                                <a href="{{route('home')}}" class="nav-link @if('admin.index'==Route::currentRouteName()) active @endif"><i class="fas fa-home mr-2"></i>Home</a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('category.index')}}" class="nav-link @if('category.index'==Route::currentRouteName()) active @endif">
                                    <i class="fas fa-boxes mr-2"></i>Categories managment
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('welcomeset.index')}}" class="nav-link @if('welcomeset.index'==Route::currentRouteName()) active @endif">
                                    <i class="fas fa-cogs mr-2"></i>Welcome settings
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('aprove.index')}}" class="nav-link @if('aprove.index'==Route::currentRouteName()) active @endif">
                                        <i class="fas fa-thumbs-up mr-2"></i>Articles approval
                                </a>
                            </li>
                            @foreach ($categories as $category)
                            <li class="nav-item">
                                <a href={{route('category.show', $category->id)}} class="nav-link @if(isset($id))@if($category->id==$id) active @endif @endif">
                                    {{ $category->name }}
                                </a>
                            </li>
                            @endforeach
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <div class="page-wrapper">
            <div class="min-vh-100">
                @yield('content')
            </div>
            <footer class="py-5 bg-dark">
                <div class="container">
                    <p class="m-0 text-center text-white">Copyright &copy; <a href="" target="_blank">SoftChamp Inc</a> 2019</p>
                </div>
            </footer>
        </div>
    </div>
    <script src="/js/jquery/jquery.min.js"></script>
    <script src="/js/bootstrap/bootstrap.bundle.min.js"></script>
    <script src="/js/jquery/jquery.easing.min.js"></script>
    <script src="/js/sb-admin-2.min.js"></script>
    <script src="{{asset('js/script.js')}}"></script>
    <script src="{{asset('js/cropper.js')}}"></script>
    <script src="{{asset('js/app.js')}}"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous"
        src="https://connect.facebook.net/ro_RO/sdk.js#xfbml=1&version=v3.3&appId=406720239939704&autoLogAppEvents=1">
    </script>
</body>
</html>