routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('command', function () {
    \Artisan::call('migrate');
    dd("Done");
});


Route::group(['middleware' => ['role']], function(){

    Route::get('/', 'WelcomeController@index')->name('welcome.index');
    Route::get('/ads.txt', 'WelcomeController@adsTxt')->name('welcome.adsTxt');
    
    Route::resource('welcome', 'WelcomeController');
    Auth::routes();
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('admin', 'Admin\AdminController');
    Route::resource('image/upload', 'Admin\ImagesController');
    Route::resource('category', 'Admin\CategoryController');
    Route::put('category-name/{category}', 'Admin\CategoryController@updateName')->name('category.name.update'); 
   
    Route::put('category/setOnWelcome/{id}', 'Admin\CategoryController@setOnWelcome')->name('category.setOnWelcome'); 
    
    Route::resource('post', 'Admin\PostController')->except([
        'create'
    ]); 
    Route::get('/post/create/{id}', 'Admin\PostController@create')->name('post.create'); 
    Route::put('/post/setOnCategory/{id}', 'Admin\PostController@setOnCategory')->name('post.setOnCategory'); 
    Route::resource('draft', 'Admin\DraftController');
    Route::resource('aprove', 'Admin\AproveController');
    Route::get('/aprove/showRejected/{id}', 'Admin\AproveController@showRejected')->name('aprove.showRejected'); 
    Route::resource('welcomeset', 'Admin\WelcomeSettingsController');
    Route::get('/welcomeset/firstSlidetGet/{id}', 'Admin\WelcomeSettingsController@firstSlidetGet')->name('welcomeset.firstSlidetGet'); 

    Route::PUT('welcomeset/updateFirstSlider/{id}', 'Admin\WelcomeSettingsController@updateFirstSlider')->name('welcomeset.updateFirstSlider'); 
    
    
    
    Route::resource('ucategory', 'User\CategoryController');
    Route::resource('articles', 'User\PostController');
    Route::resource('uposts', 'User\PostController');

    Route::resource('redactor', 'Redactor\RedactorController');






    
    
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name','index'
    ];

    static function getLastIndex()
    {
        return self::orderBy('index', 'desc')->first()->index;
    }

    // public function lang(){
    //     return $this->belongsTo('App\Lang','lang_id');
    // }

    public function posts(){
        return $this->hasMany('App\Post',"cat_id")->where('aprove',1)->where('draft',0)->orderBy('updated_at', 'desc');
    }

    public function draft(){
        return $this->hasMany('App\Post',"cat_id")->where('draft',1)->orderBy('updated_at', 'desc');
    }

    public function userPosts(){
        return $this->hasMany('App\Post',"cat_id")->where('aprove',1)->where('draft',0)->where('category_head',0)->orderBy('updated_at', 'desc');
    }
    
    public function headPost(){
        return $this->hasOne('App\Post',"cat_id")->where('aprove',1)->where('draft',0)->where('category_head',1);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;


use App\Post;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('index', 'asc')->get();
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $index = Category::getLastIndex() + 1;
        $category = Category::create([
            'name' => $request['category'],
            'index' => $index
        ]);
      
        $html = view('admin.categories.components.newCategoryLi', compact('category'))->render();
        return json_encode($html);
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category=Category::find($id);
        $posts = Post::where('cat_id', $id)->where('aprove',1)->where('draft',0)->orderBy('updated_at', 'desc')->paginate(6);
        return view('admin.categories.show', compact('id', 'posts','category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    { 
        $pass = 'false';
        if ($request['data'] == 'up' && $request['index'] != Category::orderBy('index', 'asc')->first()->index) // daca este egal cu primul element din lista, nu faci nimic
        {
            $saveCategory = Category::orderBy('index', 'desc')->where('index', '<', $request['index'])->first(); // alage primul cel mai mic element dupa request['index']
            $category -> update([
                'index' => $saveCategory->index
            ]);

            $saveCategory -> update([
                'index' => $request['index']
            ]);

            $pass = 'true';

        } else if ($request['data'] == 'down' && $request['index'] != Category::orderBy('index', 'desc')->first()->index) // daca este egal cu ultimul element din lista, nu faci nimic
        {
            $saveCategory = Category::orderBy('index', 'asc')->where('index', '>' ,$request['index'])->first(); // alage primul cel mai mare element dupa request['index']
            $category->update([
                'index' => $request['index'] + 1
            ]);

            $saveCategory->update([
                'index' => $request['index']
            ]);

            $pass = 'true';
        }
        if ($pass == 'true') {
            $categories = Category::orderBy('index', 'asc')->get();
            $html = view('admin.categories.components.updatedIndex', compact('categories'))->render();
            return json_encode($html);
        } else
            return 0;
          
    }
    
    public function updateName(Request $request, Category $category)
    {
        $category->update([
            'name' => $request['name']
        ]);
        $html = view('admin.categories.components.updatedCategoryName', compact('category'))->render();
            return json_encode($html);
        return 1;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        $categories = Category::orderBy('index', 'asc')->get();
        $html = view('admin.categories.components.updatedIndex', compact('categories'))->render();
        return json_encode($html);
    }

    public function setOnWelcome($id){
        $categories=Category::all();
        foreach($categories as $category){
            $category->on_welcome=0;
            $category->save();
        }
        Category::where('id',$id)->update([
            'on_welcome'=>1
        ]);
        return 1;
    }
}

app/Http/Controllers/User/CategoryController.php
<?php

namespace App\Http\Controllers\User;

use App\Post;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $posts=Post::inRandomOrder()->where('draft',0)->where('aprove',1)->where('category_head',0)->get();
        if(count($posts)>=4){
            $posts=Post::inRandomOrder()->where('draft',0)->where('aprove',1)->where('category_head',0)->take(3)->get();
        }
        $category=Category::find($id);
        $categoryPosts=Post::where('cat_id',$id)->where('draft',0)->where('aprove',1)->where('category_head',0)->orderBy('updated_at', 'desc')->paginate(12);
        return view('category',compact('id','category','posts','categoryPosts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/categories/index.blade.php
@extends('layouts.'.Auth::user()->userRole->role->default_page)
@section('content')
<div class="container div-table">
    <div class="row d-none d-md-flex">
        <div class="col-md-9 p-3 m-table">Categoria</div>
        <div class="col-md-1 p-3 text-center m-table">Index</div>
        <div class="col-md-1 p-3 text-center m-table">Edit</div>
        <div class="col-md-1 p-3 text-center m-table">Delete</div>
    </div>

    @foreach ($categories as $category)

    <div class="row mt-md-0 mt-3 d-flex">
        <div class="div-category-name-{{$category->id}} col-md-6 p-3 m-table d-flex align-items-center justify-content-md-start justify-content-center">
            {{$category->name}}
        </div>
        <div class="col-md-3 text-center m-table align-middle d-flex align-items-center">
            <div class="custom-control custom-switch">
                <input  type="checkbox" class="custom-control-input switch-category-welcome" data-id="{{$category->id}}" data-url="{{route('category.setOnWelcome',$category->id)}}" id="switch-category-{{$category->id}}">
                <label class="custom-control-label" for="switch-category-{{$category->id}}">Setează pe welcome</label>
            </div> 
        </div>
        <div class="col-md-1 p-3 text-center m-table">
            <button class="btn btn-sm up-btn" data-index={{$category->index}} data-url={{ route('category.update', $category->id) }}>
                <i class="fas fa-caret-up icon-black icon-arrow-size"></i>
            </button>
            <button class="btn btn-sm down-btn" data-index={{$category->index}} data-url={{ route('category.update', $category->id) }}>
                <i class="fas fa-caret-down icon-black icon-arrow-size"></i>
            </button>
        </div>
        <div class="col-md-1 p-2 text-center m-table d-flex align-items-center justify-content-center">
            <button class="btn" data-toggle="modal" data-target="#edit-category-modal-{{$category->id}}">
                <i class="fas fa-pencil-alt icon-black"></i>
            </button>
        </div>
        <div class="col-md-1 p-2 text-center m-table align-middle d-flex align-items-center justify-content-center">
            <button data-id="{{$category->id}}" class="btn btn-delete-category" data-url={{route('category.destroy', $category->id)}}> 
                <i class="fas fa-trash-alt icon-black"></i>
            </button>
        </div>
    </div>

    
    {{-- modal de edit --}}

    <div class="modal fade" id="edit-category-modal-{{$category->id}}" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">Edit</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row justify-content-center">
                        <div class="col-md-10">
							<input type="text" class="form-control" value={{$category->name}} id="input-edit-category-{{$category->id}}">
						</div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary btn-edit-category-name" data-id={{$category->id}}
                        data-url={{route('category.name.update', $category->id)}}>Save changes</button>
                </div>
            </div>
        </div>
    </div>

    @endforeach
</div>
@endsection

resources/views/admin/categories/show.blade.php
@extends('layouts.'.Auth::user()->userRole->role->default_page)
@section('content')
<div class="container-fluid">

    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link py-2 px-2 active" href="">Postări</a>
        </li>
        <li class="nav-item">
            <a class="nav-link py-2 px-2" href="{{route('draft.show',$category->id)}}">Draft</a>
        </li>
        <li class="nav-item">
            <a class="nav-link py-2 px-2" href="{{route('aprove.showRejected',$category->id)}}">Neaprobate</a>
        </li>
        <li class="nav-item">
            <a class="nav-link py-2 px-2" href="{{route('aprove.show',$category->id)}}">În proces</a>
        </li>
    </ul>
    <div class="row mt-2">
        <div class="col-md-12">
            <a href={{route('post.create', $id)}} class='round-btn-primary float-right btn-circle'><i class="fas fa-plus"></i></a>
        </div>
    </div>
    
    <div class="row mb-3">
        @foreach ($posts as $post)
            <div class="col-md-4 mt-4">
                <a href="{{route('post.show', $post->id)}}">
                    <div class="card border-0 bg-dark text-dark font-weight-bold">
                        <img src="/posts/images/{{$post->img}}" height="300px" class="card-img" alt="...">
                        <div class="background-post">
                        </div>
                        <div class="card-img-overlay ">
                            <h5 class="card-title card-title-post">{{$post->title}}</h5>
                            <p class="align-items-end card-text card-text-post">Adăugat de {{$post->user->name}}</p>
                           @if(Auth::user()->userRole->role->default_page=="admin")
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="custom-control custom-switch">
                                        <input data-url="{{route('post.setOnCategory',$post->id)}}" type="checkbox" class="custom-control-input switch-post" data-id="{{$post->id}}" id="switch-post-{{$post->id}}" @if($post->category_head==1) checked @endif>
                                        <label class="custom-control-label text-white" for="switch-post-{{$post->id}}">Setează la început</label>
                                    </div>
                                </div>
                            </div>
                            @endif

                        </div>
                    </div>
                </a>
            </div>
        @endforeach
    </div>
    <div class="row">
        <div class="col-md-4">
            {{ $posts->onEachSide(0)->links() }}
        </div>
    </div>
</div>

@endsection